modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-only"
[[mods]]
modId="citresewn"
version="${version}"
displayName="CIT Resewn"
logoFile="logo.png"
description='''
Re-implements MCPatcher's CIT
'''
credits="SHsuperCM"
authors="SHsuperCM, Asek3"
